import DataForm from "@/src/contexts/DataForm";
import "./globals.css";
import "@assets/tooltip.scss";
import { Inter } from "next/font/google";
import "@/src/assets/fontawesome/css/all.css";
import Sidebar from "@/core/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-1">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
